name: MultiArchDockerBuild

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master


jobs:
  build_multi_arch_image:
    name: Build multi-arch Docker image.
    runs-on: ubuntu-latest
    env:
      GH_REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
      REPOSITORY: playfun
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.GH_REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract metadata for release Docker image
        if: github.ref == 'refs/heads/master'
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ${{ env.GH_REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest
            type=ref,event=branch
            type=ref,event=pr
            

      - name: Extract metadata for develop Docker image
        if: github.ref != 'refs/heads/master'
        id: meta-develop
        uses: docker/metadata-action@v3
        with:
          images: |
            ${{ env.GH_REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr

      - name: Build and push master Docker image
        if: github.ref == 'refs/heads/master'
        uses: docker/build-push-action@v4
        with:
          target: deploy
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

          platforms: linux/amd64,linux/arm64
          cache-from: type=gha,scope=${{ github.workflow }}
          cache-to: type=gha,mode=max,scope=${{ github.workflow }}

      - name: Build and push feature branch Docker image
        if: github.ref != 'refs/heads/master'
        uses: docker/build-push-action@v4
        with:
          target: deploy
          push: true
          tags: ${{ steps.meta-develop.outputs.tags }}
          labels: ${{ steps.meta-develop.outputs.labels }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          cache-from: type=gha,scope=${{ github.workflow }}
          cache-to: type=gha,mode=max,scope=${{ github.workflow }}